### ISSUE TITLE
[BUG] Unable to get responses from Claude 3 Opus

### ISSUE THREAD

**Issue by axelpina** [aws-samples/bedrock-claude-chat#527]
## Describe the bug

Simply choosing Claude 3 (Opus) and sending any request, generates an error and response isn't received. This only happens with Opus. I've done extensive testing using the rest of the Models and they work well. Opus is the only one that is presenting issues.

## To Reproduce

1. Go to Chat
2. Click on Claude 3 (Opus)
3. Type any request
4. Wait for response
5. See error and check Console

## Screenshots

Image of the error:

![image](https://github.com/user-attachments/assets/1ce58bb3-b174-40e5-8944-79ea7863485f)

Model access in `us-east-1`

![image](https://github.com/user-attachments/assets/1e01c8b2-9309-4a4e-a05b-f6249b4ff682)

Cross-region inference status

![image](https://github.com/user-attachments/assets/77fd4a54-f6cb-4b9d-a3a4-3e3889265aa7)

### Additional context

Chatbot is deployed on `us-east-1`

**Comment by samhays** [comment]
Cross Region inference profiles are required in us-east-1 and I don't believe that has been added yet

**Comment by chm10** [comment]
The us-east-1 now have cross region inference for anthropic models , the Claude 3 Opus is exclusive only avaialble for cross region inference this issue is related with https://github.com/aws-samples/bedrock-claude-chat/issues/508. Some people cannot access the claude sonnet 3.5 from EU region because its is only available in cross region inference. 

![image](https://github.com/user-attachments/assets/cf08fa6d-4c5a-4cf2-a2fa-a3bf18432a70)

![367586872-27686e61-ebaf-4382-af6c-9e23887053e9](https://github.com/user-attachments/assets/5237b85d-9ec2-4de5-9c78-66b4bc648905)
